sudo: required
services:
    - docker
before-install:
    - docker build -t lek/docker-react -f Dockerfile.dev .
    # -t ใส่เพื่อสร้าง tag เอาไว้อ้างอิงหลังจาก docker build เสร็จเราจะไม่ต้องใช้ container id อีก

    script:
    - docker run -e CI=true lek/docker-react npm run test

deploy:
    provider: elasticbeansstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-827548463164"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: AKIAIJOIJQOKRG2KE2PQ
    secret_access_key: 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

    DockerReact-env.eba-mkvdm32v.us-east-2.elasticbeanstalk.com 
