sudo: required
services:
    - docker
before-install:
    - docker build -t lek/docker-react -f Dockerfile.dev .

    script:
    - docker run -e CI=true lek/docker-react npm run test

deploy:
    provider: elasticbeansstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-827548463164"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCRESS_KEY
    secret_access_key: $AWS_SECRET_KEY
